- hosts: target_group
  become: true
  gather_facts: no
  tasks: 
  - name: make sure APT DB is up-to-date
    apt:
      update_cache: yes
  - name: install nginx
    apt:
      name: nginx
      state: present
  - name: enable and start nginx
    systemd:
      name: nginx
      enabled: yes
      state: started
  - name: upload nginx config
    copy:
      src: ubuntu-fs/etc/nginx/sites-available/default
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: '0644'
  - name: upload hello-world app code
    copy:
      src: ubuntu-fs/var/www/html/hello.py
      dest: /var/www/html/hello.py
      owner: root
      group: root
      mode: '0755'
  - name: install python3-pip to install required Python module(s)
    apt:
      name: python3-pip
      state: present
  - name: install Python flup module for hello-world app
    command: pip3 install flup
  - name: install supervisor to manage FastCGI socket between nginx and hello-world app
    apt:
      name: supervisor
      state: present
  - name: enable and start supervisor
    systemd:
      name: supervisor
      enabled: yes
      state: started
  - name: upload supervisor config file for managing FastCGI socket
    copy:
      src: ubuntu-fs/etc/supervisor/conf.d/hello-fcgi.conf
      dest: /etc/supervisor/conf.d/hello-fcgi.conf
      owner: root
      group: root
      mode: '0644'
  - name: reload supervisor for it to handle the new config
    systemd:
      name: supervisor
      state: reloaded
  - name: install Postgres SQL RDBMS
    apt:
      name: postgresql
      state: present
  - name: install postgres_* modules dependency
    apt:
      name: python-psycopg2
      state: present
  - name: create a sample Postgres DB
    become_user: postgres
    postgresql_db:
      name: noctaskdb
  - name: —Åreate a sample Postgres user
    become_user: postgres
    postgresql_user:
      db: noctaskdb
      name: noc
      password: kQTVFqpFuqo
  - name: GRANT ALL PRIVILEGES ON DATABASE noctaskdb TO noc
    become_user: postgres
    postgresql_privs:
      db: noctaskdb
      privs: ALL
      type: database
      role: noc